//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DateFix.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DateFix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not one of the recognized words ({0} / {1}).
        /// </summary>
        internal static string BooleanParseError {
            get {
                return ResourceManager.GetString("BooleanParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory specified more than once..
        /// </summary>
        internal static string ErrorDirectorySpecifiedMoreThanOnce {
            get {
                return ResourceManager.GetString("ErrorDirectorySpecifiedMoreThanOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected value for argument: {0}.
        /// </summary>
        internal static string ErrorExpectedValue {
            get {
                return ResourceManager.GetString("ErrorExpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While parsing the command line arguments: {0}.
        /// </summary>
        internal static string ErrorParsingCommandLine {
            get {
                return ResourceManager.GetString("ErrorParsingCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: {0}.
        /// </summary>
        internal static string ErrorTemplate {
            get {
                return ResourceManager.GetString("ErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value for argument: {0}.
        /// </summary>
        internal static string ErrorUnexpectedValue {
            get {
                return ResourceManager.GetString("ErrorUnexpectedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized argument: {0}.
        /// </summary>
        internal static string ErrorUnrecognizedArgument {
            get {
                return ResourceManager.GetString("ErrorUnrecognizedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While processing &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorWhileProcessing {
            get {
                return ResourceManager.GetString("ErrorWhileProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to While touching &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string ErrorWhileTouching {
            get {
                return ResourceManager.GetString("ErrorWhileTouching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string for the program help.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing &apos;{0}&apos;....
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touching &apos;{0}&apos;....
        /// </summary>
        internal static string Touching {
            get {
                return ResourceManager.GetString("Touching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date specified without time, time will be set to 00:00:00..
        /// </summary>
        internal static string WarningDateSpecifiedWithoutTime {
            get {
                return ResourceManager.GetString("WarningDateSpecifiedWithoutTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate argument &apos;{0}&apos;, second value will take over..
        /// </summary>
        internal static string WarningDuplicateArgument {
            get {
                return ResourceManager.GetString("WarningDuplicateArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No dates selected to be changed. Exiting early..
        /// </summary>
        internal static string WarningNoDatesToSet {
            get {
                return ResourceManager.GetString("WarningNoDatesToSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: {0}.
        /// </summary>
        internal static string WarningTemplate {
            get {
                return ResourceManager.GetString("WarningTemplate", resourceCulture);
            }
        }
    }
}
